var widthVideo_0 = "700";
var heightVideo_0= "513";

var httpMail = "mailto:lee@newhopeceramics.com";
var httpString_0 = "http://www.youtube.com/embed/";
var httpString_1 = "https://player.vimeo.com/video/";

var dirAdd_Audio = "media/audio/";
var dirAdd_IMG = "media/img/";
var dirAdd_Video = "media/mov/";
var dirAdd_Text = "media/text/";

//navUpper--------------------_
var imgStyle = "width:80px;height:80px;border:0;"
var audioStyle = ""
var videoStyle = ""
var mainMedia = [
{
"name": "Bowls",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Bowls","",""],
"concept": ["Clear Glaze Bowls","",""],
"mainTag": "#Bowls",
"myTag":"#All#Bowls#kitchen#Color",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Bowls/BB_0_2.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Bowls/B_0_0.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Bowls/B_0_1.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Bowls",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Bowls","",""],
"concept": ["Floral Glaze Bowls","",""],
"mainTag": "#Bowls",
"myTag":"#All#Bowls#kitchen#Floral",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Bowls/BBf_0_2.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Bowls/Bf_1_1.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Bowls/Bf_0_1.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Containers",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Containers"],
"concept": ["Clear Glaze Vessels"],
"mainTag": "#Containers",
"myTag":"#All#Containers#kitchen#Color",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Containers/Containers_5.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Containers",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Containers"],
"concept": ["White And Clear Glaze Containers"],
"mainTag": "#Containers",
"myTag":"#All#Containers#kitchen#White",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Containers/Containers_1.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Containers",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Containers"],
"concept": ["Clear Glaze Containers"],
"mainTag": "#Containers",
"myTag":"#All#Containers#kitchen#White",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Containers/Containers_2.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Containers",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Containers"],
"concept": ["Clear Glaze Containers"],
"mainTag": "#Containers",
"myTag":"#All#Containers#kitchen#White",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Containers/Containers_4.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Pitchers",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Pitchers"],
"concept": ["White And Floral Glaze Pitchers"],
"mainTag": "#Pitchers",
"myTag":"#All#Pitchers#kitchen",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Pitchers/P_PW_6_2.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Pitchers",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Pitchers"],
"concept": ["White Glaze Pitchers"],
"mainTag": "#Pitchers",
"myTag":"#All#Pitchers#kitchen#White",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Pitchers/PW_0_1.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Pitchers",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Pitchers"],
"concept": ["Floral Glaze Pitchers"],
"mainTag": "#Pitchers",
"myTag":"#All#Pitchers#kitchen#Floral",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Pitchers/P_2_0.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Platters",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Platters"],
"concept": ["Color Glaze Platters"],
"mainTag": "#Platters",
"myTag":"#All#Platters#kitchen#Color",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Platters/Platters_0.JPG",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Platters",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Handbuilt Platters","",""],
"concept": ["Square","Oval","_"],
"mainTag": "#Platters",
"myTag":"#All#Platters#kitchen#Color#Handbuilt",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Platters/Platters_2.JPG",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Platters/Platters_4.JPG",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Platters/Platters_5.JPG",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Knitting Bowls",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Knitting Bowls"],
"concept": [""],
"mainTag": "#Platters",
"myTag":"#All#Bowls#Knitting#Knitting Bowls#Color",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Bowls/KBowls_0.JPG",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Lamps",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Lamps",""],
"concept": ["",""],
"mainTag": "#Lamps",
"myTag":"#All#Lamps",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Lamps/Lamps_0.JPG",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Lamps/Lamps_1.JPG",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Tile",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Floral Tile"],
"concept": [""],
"mainTag": "#Tile",
"myTag":"#All#Tile#Floral",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Tile/Tiles_1.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Vessels",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Floral Vessels","","","","",""],
"concept": ["","","","","",""],
"mainTag": "#Vessels",
"myTag":"#All#Vessels#Floral",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_V_V_0_0.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_0_2.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_4_2.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_V_0_1.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_6_0.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_5_0.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Vessels",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Color Vessels"],
"concept": [""],
"mainTag": "#Vessels",
"myTag":"#All#Vessels#Color",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_1_0.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Vessels",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["White Vessels"],
"concept": [""],
"mainTag": "#Vessels",
"myTag":"#All#Vessels#White",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Vessels/V_V_3_0.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Process",
"date": "Jan 1, 2020",
"url": "",
"srcName": ["Process","","","","","","","","","",""],
"concept": ["","","","","","","","","","",""],
"mainTag": "#Process",
"myTag":"#All#Process",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-03-27 12.16.32.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-04-15 20.51.00.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-05-03 10.13.06.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-05-10 11.51.37.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-05-14 09.37.10.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-05-14 14.28.48.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-05-15 11.36.54.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-07-17 11.18.15.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-07-21 16.25.55.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-08-07 14.17.40.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Process/2019-08-14 06.09.49.jpg",
		"style": imgStyle,
		"alt": "",
		}
		],
"links":[
		{
		"srcName": "",
		"url": "",
		"downloads": "",
		"displayTitle": "link to",
		"acckey": "",
		"display": "",
		}
		],
},
{
"name": "Ceramics",
"date": "Jan 1, 2001",
"url": "",
"srcName": ["Building The Studio","","","","","","","","",""],
"concept": ["","","","","","","","","",""],
"mainTag": "#Building",
"myTag":"#All#Building#Studio",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_0.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_1.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_3.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_4.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_5.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_6.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_7.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_10.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_11.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Building/Building_8.jpg",
		"style": imgStyle,
		"alt": "",
		},
		],
"links":[
		{
		"srcName": "Flickr",
		"url": "https://www.flickr.com/photos/antisuji/albums/72157647565271623",
		"downloads": "",
		"displayTitle": "link to Flickr",
		"acckey": "",
		"display": "Flickr",
		}
		],
},
{
"name": "Ceramics",
"date": "Jan 1, 2001",
"url": "",
"srcName": ["Ceramics","","","","","","","","","","","","","","","","","","","",""],
"concept": ["Clear Glaze Vessels","_","_","_","_","_","_","_","_","_","_","_","_","_","_","_","_","_","_","_","Ceramics Pic at Flickr"],
"mainTag": "#Ceramics",
"myTag":"#All#Ceramics",
"audio":[
		{
		"url": "",
		"url_P": "",
		"width": "300",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Audio + "",
		"img": "",
		"style": audioStyle,
		}
		],
"video":[
		{
		"url": "",
		"url_P": "",
		"width": "140",
		"height": "40",
		"autostart": "false",
		"loop": "FALSE",
		"displayTitle": "link to",
		"display": "Test",
		"file": dirAdd_Video + "",
		"img": "",
		"style": videoStyle,
		}
		],
"iconsImg":[	
		{
		"url": "",
		"url_P": "",
		"width": "100",
		"height": "100",
		"displayTitle": "link to Topic",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navTopic/CeramicsTopic_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		},
		{
		"url": "",
		"url_P": "",
		"width": "231",
		"height": "100",
		"displayTitle": "link to Rel",
		"acckey": "",
		"display": "Test",
		"img": dirAdd_IMG + "myIcons/navRelated/CeramicsRelated_0.jpg",
		"style": imgStyle,
		"alt": "Test Work",
		}
		],
"srcImg":[
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Containers/Containers_5.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Containers/Containers_0.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_2.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_3.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_4.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_5.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_6.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_7.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_8.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_9.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_10.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_11.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_12.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_13.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_14.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_15.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_16.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_17.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_18.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/the_ceramics_still_have_19.jpg",
		"style": imgStyle,
		"alt": "",
		},
		{
		"url": "",
		"url_P": "",
		"width": "",
		"height": "",
		"displayTitle": "link to Ceramics",
		"acckey": "",
		"display": "",
		"mode": "0",
		"img": dirAdd_IMG + "Ceramics/pots.jpg",
		"style": imgStyle,
		"alt": "",
		},
		],
"links":[
		{
		"srcName": "Flickr",
		"url": "https://www.flickr.com/photos/antisuji/albums/72157647565271623",
		"downloads": "",
		"displayTitle": "link to Flickr",
		"acckey": "",
		"display": "Flickr",
		}
		],
}
];
